FROM node:20-alpine AS base

FROM base AS deps

WORKDIR /home/node/app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
elif [ -f package-lock.json ]; then npm ci; \
elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
else echo "Lockfile not found." && exit 1; \
fi

FROM base AS builder

WORKDIR /home/node/app

COPY --from=deps /home/node/app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM base AS runtime

ENV NODE_ENV=production
ENV PAYLOAD_CONFIG_PATH=dist/payload.config.js

WORKDIR /home/node/app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

COPY --from=builder /home/node/app/node_modules ./node_modules
COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/build ./build
COPY ./assets ./assets

EXPOSE 3000

CMD ["node", "dist/server.js"]
