import { Post, PostType } from "@/types/community";

// Mock posts data
const basePosts: Post[] = [
  {
    id: "post-1",
    title: "Nieuwe isolatietechniek voor platte daken",
    content: "Ik heb onlangs een nieuwe isolatietechniek toegepast bij een project die echt fantastisch werkt. Het betreft een combinatie van PIR-platen met een reflecterende laag. De warmteweerstand is aanzienlijk verbeterd.\n\nHeeft iemand hier ervaring mee? Ik ben benieuwd naar jullie ervaringen en tips.",
    authorId: "user-1",
    authorName: "Jan Dekker",
    authorAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-4",
    groupName: "Technisch advies",
    type: PostType.TECHNICAL_ADVICE,
    likeCount: 24,
    dislikeCount: 2,
    commentCount: 8,
    media: [
      {
        id: "media-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1605095141947-6c41d79fca19?auto=format&fit=crop&q=80&w=1000",
      },
      {
        id: "media-2",
        type: "image",
        url: "https://images.unsplash.com/photo-1625472603517-1b0dc8ecc3cd?auto=format&fit=crop&q=80&w=1000",
      }
    ],
  },
  {
    id: "post-2",
    title: "Dakdekker gezocht voor groot project in Rotterdam",
    content: "Wij zijn op zoek naar ervaren dakdekkers voor een groot project in Rotterdam. Het betreft een nieuwbouwproject met ongeveer 30 woningen. Start: februari 2025. Duur: ongeveer 3 maanden. Goede betaling en mogelijkheid voor langdurige samenwerking. Stuur een bericht bij interesse!",
    authorId: "user-2",
    authorName: "Bouwbedrijf De Toekomst",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-2",
    groupName: "Werk en personeel",
    type: PostType.JOB_LISTING,
    likeCount: 7,
    dislikeCount: 0,
    commentCount: 12,
  },
  {
    id: "post-3",
    title: "Mijn laatste project: renovatie monumentaal pand",
    content: "Eindelijk klaar met de renovatie van dit monumentale pand in Utrecht. Het was een uitdagend project vanwege de historische waarde en de vele details in het dak. We hebben bijzondere leien gebruikt die speciaal geïmporteerd zijn. Trots op het resultaat!",
    authorId: "user-3",
    authorName: "Michael van Dijk",
    authorAvatar: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-3",
    groupName: "Project showcases",
    type: PostType.PROJECT_SHOWCASE,
    likeCount: 47,
    dislikeCount: 0,
    commentCount: 16,
    media: [
      {
        id: "media-3",
        type: "image",
        url: "https://images.unsplash.com/photo-1599619351208-3e6c839d6828?auto=format&fit=crop&q=80&w=1000",
      },
      {
        id: "media-4",
        type: "image",
        url: "https://images.unsplash.com/photo-1604014236812-0389b1263bb1?auto=format&fit=crop&q=80&w=1000",
      },
      {
        id: "media-5",
        type: "image",
        url: "https://images.unsplash.com/photo-1605276374105-dee8cbbbaecd?auto=format&fit=crop&q=80&w=1000",
      }
    ],
  },
  {
    id: "post-4",
    title: "Vragen over garantiebepaling bij lekkage",
    content: "Ik heb vorig jaar een dak vervangen voor een klant. Nu klaagt de klant over lekkage die volgens hem onder de garantie valt. Maar bij inspectie blijkt dat de lekkage komt door een beschadiging die later is ontstaan (waarschijnlijk door werkzaamheden van een andere partij).\n\nHoe gaan jullie hiermee om? Ben ik verplicht dit kosteloos te herstellen onder de garantie?",
    authorId: "user-4",
    authorName: "Peter Vos",
    authorAvatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-5",
    groupName: "Juridisch advies",
    type: PostType.LEGAL_ADVICE,
    likeCount: 3,
    dislikeCount: 0,
    commentCount: 9,
  },
  {
    id: "post-5",
    title: "Zoek partner voor groot zonnedak project",
    content: "Wij hebben een grote opdracht binnengehaald voor het plaatsen van 200+ zonnepanelen op een bedrijfspand, maar kunnen dit niet alleen aan binnen de gestelde termijn. We zoeken een betrouwbare partner om mee samen te werken. Het betreft een project in de regio Eindhoven. Start over 3 weken. Reacties graag via DM.",
    authorId: "user-5",
    authorName: "Duurzame Daken BV",
    authorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-2",
    groupName: "Werk en personeel",
    type: PostType.OUTSOURCE_WORK,
    likeCount: 12,
    dislikeCount: 0,
    commentCount: 5,
  },
  {
    id: "post-6",
    title: "Problemen met inloggen op app",
    content: "Sinds de laatste update kan ik niet meer inloggen op de app. Ik krijg steeds een foutmelding dat mijn wachtwoord niet klopt, maar ik ben zeker van mijn wachtwoord. Ik heb al geprobeerd mijn cache te wissen en de app opnieuw te installeren. Heeft iemand hetzelfde probleem of een oplossing?",
    authorId: "user-6",
    authorName: "Thomas Bosman",
    authorAvatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&q=80&w=50&h=50",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    groupId: "group-6",
    groupName: "Support vragen",
    type: PostType.GENERAL,
    likeCount: 1,
    dislikeCount: 0,
    commentCount: 3,
  },
];

export const getBasePosts = (): Post[] => [...basePosts];
