# .github/workflows/deploy-frontend.yml
name: Deploy Frontend (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/bmsservices-flexavi/htdocs/flexavi.bmsservices.id/flexavi-fe
            git reset --hard origin/main
            git pull origin main
            npm ci
            npm run build