# .github/workflows/deploy-frontend.yml
name: Deploy Frontend to MijnHost and Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy-to-mijnhost:
    name: Deploy to MijnHost
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to MijnHost
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MIJN_HOST }}
          port: 26
          username: ${{ secrets.MIJN_USER }}
          key: ${{ secrets.MIJN_KEY }}
          script: |
            cd /domains/demov4.flexavi.nl/dist
            git reset --hard origin/main
            git pull origin main
            npm ci
            npm run build

  deploy-to-hostinger:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/bmsservices-flexavi/htdocs/flexavi.bmsservices.id/flexavi-fe
            git reset --hard origin/main
            git pull origin main
            npm ci
            npm run build